<section class="post-hero">
    <div class="container post-hero-grid">
        <div class="post-cover"><?php if($post['image_url']): ?><img src="<?= e($post['image_url']) ?>" alt="<?= e($post['title']) ?>"><?php else: ?><div class="post-cover-fallback"><?= e(strtoupper(substr($post['country'],0,2))) ?></div><?php endif; ?></div>
        <div><span class="cost-tag cost-<?= e(strtolower($post['cost_level'])) ?>"><?= e($post['cost_level']) ?></span><h1><?= e($post['title']) ?></h1><div class="meta large">&#128205; <?= e($post['country']) ?> &middot; <?= e($post['category']) ?></div><p class="lead"><?= nl2br(e($post['short_history'])) ?></p><div class="byline">Verified Scout Content &middot; <?= e($post['scout_name'] ?? 'TravelGuide') ?></div>
        <?php if(is_logged_in()): ?><form class="inline-form" method="post" action="<?= e(url('wishlist/toggle')) ?>"><?= csrf_field() ?><input type="hidden" name="post_id" value="<?= (int)$post['id'] ?>"><button class="btn <?= $wishlisted?'btn-soft':'btn-primary' ?>" type="submit"><?= $wishlisted?'Remove from Wishlist':'Add to Wishlist' ?></button></form><?php else: ?><a class="btn btn-primary" href="<?= e(url('login')) ?>">Login to Save</a><?php endif; ?>
        </div>
    </div>
</section>
<section class="section container two-col">
    <div><h2>Destination Details</h2><div class="detail-grid"><div><small>Country</small><strong><?= e($post['country']) ?></strong></div><div><small>Category</small><strong><?= e($post['category']) ?></strong></div><div><small>Cost level</small><strong><?= e($post['cost_level']) ?></strong></div><div><small>Approval</small><strong>Administrator Approved</strong></div></div><a class="btn btn-dark" href="<?= e(url('calculator')) ?>">Calculate a Trip Budget</a></div>
    <aside class="comments-panel"><h2>Comments <span>(<?= count($comments) ?>)</span></h2>
        <?php if(is_logged_in()): ?><form class="comment-form" method="post" action="<?= e(url('comment/store')) ?>"><?= csrf_field() ?><input type="hidden" name="post_id" value="<?= (int)$post['id'] ?>"><textarea name="content" maxlength="1000" required placeholder="Share your experience or ask a useful question..."></textarea><button class="btn btn-primary" type="submit">Add Comment</button></form><?php else: ?><p class="muted-box"><a href="<?= e(url('login')) ?>">Login</a> to join the discussion.</p><?php endif; ?>
        <div class="comment-list"><?php if(!$comments): ?><p class="muted">No comments yet.</p><?php endif; ?><?php foreach($comments as $comment): ?><div class="comment"><div class="comment-head"><strong><?= e($comment['name']) ?></strong><small><?= e(date('d M Y, h:i A',strtotime($comment['created_at']))) ?></small></div><p><?= nl2br(e($comment['content'])) ?></p><?php if(is_logged_in() && (int)$comment['user_id']===(int)auth()['id']): ?><form method="post" action="<?= e(url('comment/delete')) ?>" onsubmit="return confirm('Delete your comment?')"><?= csrf_field() ?><input type="hidden" name="comment_id" value="<?= (int)$comment['id'] ?>"><input type="hidden" name="post_id" value="<?= (int)$post['id'] ?>"><button class="link-danger" type="submit">Delete my comment</button></form><?php endif; ?></div><?php endforeach; ?></div>
    </aside>
</section>
