<section class="page-heading"><span class="eyebrow">FOODPLAN ADMIN</span><h1>Administration</h1><p>Manage incoming orders, the menu, delivery team, and customer support.</p></section>
<section class="section admin-layout"><nav class="admin-nav"><a href="#overview">Overview</a><a href="#orders">Orders</a><a href="#rider-requests">Rider requests</a><a href="#products">Products</a><a href="#reservations">Reservations</a><a href="#riders">Delivery team</a><a href="#customers">Customers</a><a href="#payments">Payments</a><a href="#coupons">Coupons</a><a href="#tickets">Support</a><button type="button" data-logout>Sign out</button></nav><div class="admin-content">
  <section class="panel" id="overview" data-admin-overview></section>
  <section class="panel" id="orders"><div class="section-title"><div><span class="eyebrow">FULFILLMENT</span><h2>Order management</h2></div></div><div data-admin-orders></div></section>
  <section class="panel" id="rider-requests"><h2>Rider pickup requests</h2><p class="muted">Review a rider's request before assigning a ready order.</p><div data-admin-rider-requests></div></section>
  <section class="panel" id="products"><div class="section-title"><h2>Products</h2><button class="button button-small" type="button" data-toggle-form="product-form">Add product</button></div><form class="form-grid hidden" id="product-form" data-admin-product><label>Name<input name="name" required></label><label>Category<select name="category_id" data-category-options></select></label><label>Price<input name="price" type="number" min="1" step=".01" required></label><label>Discount %<input name="discount_percent" type="number" min="0" max="100" value="0"></label><label>Stock<input name="stock" type="number" min="0" value="20"></label><label>Image URL<input name="image_url" type="url"></label><label class="span-all">Description<textarea name="description" required></textarea></label><label class="span-all">Ingredients<input name="ingredients"></label><p class="form-message span-all" data-message></p><button class="button">Save product</button></form><div data-admin-products></div></section>
  <section class="panel" id="reservations"><h2>Reservations</h2><div data-admin-reservations></div></section>
  <section class="panel" id="riders"><div class="section-title"><h2>Delivery team</h2><button class="button button-small" type="button" data-toggle-form="rider-form">Add rider</button></div><form class="form-grid hidden" id="rider-form" data-admin-rider><label>Name<input name="name" required></label><label>Email<input name="email" type="email" required></label><label>Phone<input name="phone"></label><label>Password<input name="password" type="password" minlength="8" required></label><button class="button">Create rider</button></form><div data-admin-riders></div></section>
  <section class="panel" id="customers"><h2>Customers</h2><div data-admin-customers></div></section>
  <section class="panel" id="payments"><h2>Payments</h2><div data-admin-payments></div></section>
  <section class="panel" id="coupons"><div class="section-title"><h2>Coupons</h2></div><form class="form-grid" data-admin-coupon><label>Code<input name="code" required></label><label>Type<select name="discount_type"><option value="percent">Percent</option><option value="fixed">Fixed amount</option></select></label><label>Discount<input name="discount_value" type="number" min=".01" step=".01" required></label><label>Minimum order<input name="minimum_order" type="number" min="0" value="0"></label><label>Description<input name="description"></label><button class="button">Create coupon</button></form><div data-admin-coupons></div></section>
  <section class="panel" id="tickets"><h2>Support requests</h2><div data-admin-tickets></div></section>
</div></section>
